# Generated by Django 2.1.7 on 2019-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAccInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=30, verbose_name='性别')),
                ('birth', models.DateField()),
                ('idcard', models.CharField(max_length=18)),
                ('city', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=20)),
                ('checkintime', models.DateField()),
                ('checkouttime', models.DateField()),
            ],
        ),
    ]
